spring:
  application:
    name: idear-api
  profiles:
    active: local # 기본 active profile
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  servlet:
    context-path: /api

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${LOCAL_MYSQL_URL}
    username: ${LOCAL_MYSQL_USER}
    password: ${LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${PROD_MYSQL_URL}
    username: ${PROD_MYSQL_USER}
    password: ${PROD_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update # Migration 도구 사용 고려 (validate)
    properties:
      hibernate:
        show-sql: false
