spring:
  application:
    name: idear-api
  profiles:
    active: local # 기본 active profile
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  task:
    scheduling:
      enabled: false # 스케줄러 비활성화
idear:
  crawler:
    enabled: false # 크롤러 비활성화

server:
  servlet:
    context-path: /api

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    bucket: idear-file
    region:
      static: ap-northeast-2

secret:
  jwt:
    key: ${JWT_KEY}
    access:
      expiration: 3600000
    refresh:
      expiration: 1209600000

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${LOCAL_MYSQL_URL}
    username: ${LOCAL_MYSQL_USER}
    password: ${LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true

  front:
    origin: ${FRONT_ORIGIN_LOCAL}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI_LOCAL}
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${PROD_MYSQL_URL}
    username: ${PROD_MYSQL_USER}
    password: ${PROD_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update # Migration 도구 사용 고려 (validate)
    properties:
      hibernate:
        show-sql: false

  front:
    origin: ${FRONT_ORIGIN}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
