spring:
  main:
    web-application-type: none
  task:
    scheduling:
      enabled: true

  datasource:
    url: ${PROD_MYSQL_URL}
    username: ${PROD_MYSQL_USER}
    password: ${PROD_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  front:
    origin: ${FRONT_ORIGIN}

idear:
  crawler:
    enabled: true